spring.application.name=${SPRING_APP_NAME:springSecurity}
logging.pattern.console=&{LOGG_PATTERN_CONSOLE:%d{HH:mm:ss.SSS} %clr(%-5level){red} %clr([%thread]){yellow} %clr(%logger{36}){blue} %clr(%msg){green}%n}

